services:
  db:
    container_name: tradescout_DB
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      - POSTGRES_DB=Local
      - POSTGRES_USER=tradescout
      - POSTGRES_PASSWORD=temp_pass
    ports:
      - "5432:5432"
    platform: linux/x86_64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tradescout -d Local"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: temp_pass
    ports:
      - "5051:80"

  api:
    container_name: api
    build:
      context: ./tradescout-api
      dockerfile: Dockerfile     
    restart: always
    env_file:
      - ./tradescout-api/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy


  frontend:
    container_name: ui
    build:
      context: ./tradescout-ui 
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    restart: always
    env_file:
      - ./tradescout-ui/.env
    ports:
      - "80:80"
    depends_on:
      - api