services:
  db:
    container_name: tradescout_DB
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      - POSTGRES_DB=Local
      - POSTGRES_USER=tradescout
      - POSTGRES_PASSWORD=temp_pass
    ports:
      - "5432:5432"
    platform: linux/x86_64

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: temp_pass
    ports:
      - "5051:80"

  s3Bucket:
      container_name: DocVault-s3Bucket
      image: minio/minio:latest
      ports:
        - "9000:9000"
        - "9099:9099"
      environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=admin1234
      # env_file:
      #   - .env
      command: server /data --console-address ":9099"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
  minio-setup:
      image: minio/mc:latest
      depends_on:
        s3Bucket:
          condition: service_healthy
      # env_file:
      #   - .env
      entrypoint: |
        /bin/sh -c '
        until mc alias set myminio http://s3Bucket:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
          echo "Waiting for MinIO..."
          sleep 5
        done

        mc mb myminio/docvault-bucket --ignore-existing
        mc version enable myminio/docvault-bucket

        echo "Bucket created and versioning enabled."
        '